#!/usr/bin/python

import os
import sys
import string

USERDIR = "users"
USERWHITELIST = string.letters + string.digits

def prepareDirs():
    try:
        os.makedirs(USERDIR)
    except OSError:
        pass 

def writeOut(s):
    sys.stdout.write(s)
    sys.stdout.flush()

def reportOut(s):
    sys.stderr.write(s)
    sys.stderr.flush()

def validateAndLogin(username, password):
    
    if not all(map(lambda c: c in USERWHITELIST, username)):
        return "invalid username" 

    userEntry = os.path.join(USERDIR, username, 'password')

    if os.path.exists(userEntry):
        recordPassowrd = ""
        with open(userEntry, 'r') as f:
            recordPassword = f.read()

        if recordPassword == password:
            return "granted:%s" % username
        else:
            return "denied"
    else:
        return "no such user"

def createUserEntry():
    writeOut("Username: ")

    username = sys.stdin.readline().strip()

    writeOut("Password: ")

    password = sys.stdin.readline().strip()

    output = validateAndLogin(username, password)

    reportOut(output + "\n")

if __name__ == "__main__":
    prepareDirs()
    createUserEntry() 
